### ISSUE TITLE
New Majestic streamer options in config

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/microbe-web#84]
How will it be possible to add new audio system control options via GPIO to your wonderful WEB interface

 ```
 audio:
  .....
  outputEnabled: false
  speakerPin: 32
  speakerPinInvert: false
```
